log_file_path: obsidian-tools.log
dry_run: false
max_concurrent_file_operations: 10

file_names_to_ignore:
  - .DS_Store

folder_names_to_ignore:
  - .obsidian # It's not recommended to mess with this
  - .stversions
  - .git
